### ISSUE TITLE
The Contao Manager failed to start a console task!

### ISSUE THREAD

**Issue by learner-kde2020** [contao/contao-manager#563] opened 2020-06-06 10:56 UTC
After I tried to update (self-update) Contao Manager on Safari I received this message:

The Contao Manager failed to start a console task!
Something went wrong while trying to execute the task in the background.
If this happens again, your server might not be supported.

**Comment by aschempp** [comment] 2020-06-08 09:25
but the update happened successfully, right?

**Comment by aschempp** [comment] 2020-06-08 09:26
duplicate of https://github.com/contao/contao-manager/issues/479

**Closed by aschempp** 2020-06-08 09:26 UTC
