### ISSUE TITLE
Console task loads indefinitely

### ISSUE THREAD

**Issue by darkojic** [contao/contao-manager#317] opened 2018-08-08 18:51 UTC
Hello,

I am experiencing some issues with Contao installation process using latest Contao Manager (1.0.3) which I downloaded from contao.org.

I'm trying to install Contao 4.4 with Contao Manager to my paid hosting. I have created dedicated subdomain and folder "web" inside of it. 

After I placed contao-manager.phar.php inside web folder I run http://subdomain/contao-manager.phar.php and CM interface was open. I created account and logged in, but after that message "Loading console taks..." appears and later nothing happens.

![image](https://user-images.githubusercontent.com/42218572/43857505-c627492a-9b4b-11e8-9e08-e43d4b308b74.png)

I was able to find this error in my hosting logs:

`[Wed Aug 08 20:35:04 2018] [warn] [client 100.*.*.*] mod_fcgid: stderr: PHP Fatal error:  Phar::webPhar(): Failed opening required 'phar:///var/www/vhosts/***/httpdocs/alicante/web/contao-manager.phar.php/web/api.php' (include_path='.:/opt/plesk/php/5.6/share/pear') in /var/www/vhosts/***/httpdocs/alicante/web/contao-manager.phar.php on line 100, referer: https://***/contao-manager.phar.php/`

PHP Server Configuration:

> version: 5.6.37; 
> handler: FastCGI application
> include_path  .:/opt/plesk/php/5.6/share/pear (Default)
> session.save_path  /var/lib/php/session (Default)

Can I run Contao installation with Composer in this way? Or I have to switch to PHP 7.1 instead?

Thanks.

**Comment by darkojic** [comment] 2018-08-08 19:41
PS I've just found #306 being the same issue as I reported.

**Comment by darkojic** [comment] 2018-08-08 21:25
Okay, this is complete log. If someone have a clue what could be a reason... I hope it could help.

![image](https://user-images.githubusercontent.com/42218572/43865270-6229f442-9b62-11e8-9162-efad22a3046a.png)

**Comment by aschempp** [comment] 2018-08-09 06:46
Generally speaking, using PHP 5.6 is a bad idea, as the version is outdated and not supported anymore: https://secure.php.net/supported-versions.php

Regarding the issue, I haven't been able to reproduce this, so it's pretty hard to help out. But I'm closing this as duplicate of #306, please try PHP 7.1 and us know in the other ticket if the issue still exists.

**Closed by aschempp** 2018-08-09 06:46 UTC
