### ISSUE TITLE
Cloud resolving runs endlessly

### ISSUE THREAD

**Issue by dmolineus** [contao/contao-manager#279] opened 2018-06-11 11:53 UTC
I've tried to use the new cloud resolver integrated in CM 1.0.0 after a local update stopped working (memory limit 1.5G).

Unfortunately the job runs more than thousand seconds without any feedback. Tried different tasks (update all, update own package, run try) - the same behaviour.

Here the link to a job, not cancelled yet: https://resolve.contao.org/jobs/5b1e5a88bf3330.21980336

![622acc24-6acc-4071-bf4e-3f0d8c6c74b6](https://user-images.githubusercontent.com/1186266/41229963-4a3e4106-6d7e-11e8-8adf-806bc01c11bb.png)

Hoster is All Inkl. If you need more information I'm happy to provide them.

**Comment by Toflar** [comment] 2018-06-11 12:03
It might be possible that the worker actually crashed and the job got lost due to memory (like e.g. if all workers are running at the very same time and need more memory than the cloud in total provides). There's no failover to retry later yet and probably we won't have that before a few months because it's very hard to implement and needs changes in Composer (already proposed and merged for 1.7).

I could reduce the number of workers to 2 instead of 4 to reduce the probability of something like this happening.

**Comment by dmolineus** [comment] 2018-06-11 12:21
Running a composer update local with `--profile` for that composer.json consumes about 1.65 GB memory. That shouldn't be an issue if it's the single worker, shouldn't it?

The process always failed, no matter if other worker were active or not.

**Comment by Toflar** [comment] 2018-06-11 12:23
There's no way I could ever debug this. No information is collected. @aschempp do we log the request that is sent to the cloud so @dmolineus could provide us with the complete request? We might be able to reproduce it then and see what we can do.

**Comment by katgirl** [comment] 2018-06-11 18:57
Kann man das auch irgendwie abschalten? Unsere Server haben genug freien Speicher. Der Task hat sich bei mir auch mehrfach aufgehängt. Habe es dann via Konsole gemacht.

**Comment by xchs** [comment] 2018-06-11 18:58
In den Servereinstellungen kannst Du die entsprechende Option deaktivieren.

**Comment by aschempp** [comment] 2018-06-12 07:30
The development version of the manager does log the request, so that would be an option. @dmolineus can you compile that myself or want me to send it to you (e.g. on Skype)?

**Comment by dmolineus** [comment] 2018-06-18 19:58
@aschempp it would be great if you could send me a compiled version. I contact you with Skype tomorrow.

@Toflar I'll provide the composer.json tomorrow as well.

**Comment by dmolineus** [comment] 2018-06-21 06:43
As promised the composer.json which failed. It failed because of `"minimum-stability": "dev"`. Just added it again so that you can reproduce it.

[composer.json.txt](https://github.com/contao/contao-manager/files/2122443/composer.json.txt)

**Comment by Toflar** [comment] 2018-06-21 08:18
@dmolineus Thanks for providing the test case. Cloud update is currently rolling out, can you try again in like 5 minutes?

**Comment by dmolineus** [comment] 2018-06-21 08:56
:+1: Yes, it's working now.

**Comment by Toflar** [comment] 2018-06-21 08:59
Very good. BTW: Your job used 2.2GB of memory 😄

**Closed by Toflar** 2018-06-21 08:59 UTC
