### ISSUE TITLE
I cant open contao backend

### ISSUE THREAD

**Issue by amarildo2001** [contao/contao-manager#691] opened 2022-06-10 14:43 UTC
when i try to open the backend of contao it says "The requested URL was not found on this server."

url: mysubdomain/contao/install. Can someone help me

**Comment by ausi** [comment] 2022-06-10 14:47
Duplicate of #690

**Closed by ausi** 2022-06-10 14:47 UTC

**Comment by ausi** [comment] 2022-06-10 14:48
@amarildo2001 if you need help, feel free to join our Slack and ask questions there: https://to.contao.org/slack

**Comment by amarildo2001** [comment] 2022-06-10 14:54
i tried to become part of your forum, but no one approves my new account

**Comment by amarildo2001** [comment] 2022-06-10 14:54
really bad service

**Comment by amarildo2001** [comment] 2022-06-10 15:03
@ausi read my messages

**Comment by ausi** [comment] 2022-06-10 15:05
@amarildo2001 Yes, for quick answers I’d still suggest using Slack: https://to.contao.org/slack

> i tried to become part of your forum, but no one approves my new account

I will take a look into that (but that might take some time).

**Comment by amarildo2001** [comment] 2022-06-10 15:06
i dont have so much time. my project has a deadline @ausi

**Comment by amarildo2001** [comment] 2022-06-10 15:11
i didnt say anything to laaugh @ausi

**Comment by kikmedia** [comment] 2022-06-11 09:19
Unfortunately we don't approve new accounts on the english speaking forums for now. Feel free to join the german forums, where questions may also asked in the language preferred by you.

Since we are planning to merge the community forums, this will be your place to go for now and for all future questions.

Sorry for inconveniences.
