### ISSUE TITLE
Database Backup Feature

### ISSUE THREAD

**Issue by fkaminski** [contao/contao-manager#722] opened 2022-09-03 11:09 UTC
It would be nice to be able to initiate a database backup via the manager, 
analogous to the procedure via the console:
https://docs.contao.org/manual/en/cli/db-backups/

**Comment by aschempp** [comment] 2022-09-05 14:44
duplicate of https://github.com/contao/contao-manager/issues/87

**Closed by aschempp** 2022-09-05 14:44 UTC
