### ISSUE TITLE
check if PHP symlink() function is enabled

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao-manager#213] opened 2018-01-31 15:39 UTC
The Manager don't check it, so that I can install Contao without any problems, but when the task "Recreate the symlinks" will be activated or new files will be uploaded, then the symlinks for `web/files` will be broken and don't come back automatically. You have to run `composer install` or `Update packages` in Contao Manager, because via forked process it's no problem. Just with the webprocess will be a problem.

The Contao Check in the current master version check for the PHP symlink() function.

**Comment by Toflar** [comment] 2018-05-04 08:54
Duplicate of #146

**Closed by Toflar** 2018-05-04 08:54 UTC
