### ISSUE TITLE
Blank page on contao-manager after update to ubuntu 18.04

### ISSUE THREAD

**Issue by MicioMax** [contao/contao-manager#339] opened 2018-10-09 07:04 UTC
I couldn't get contao manager working on a new website, after upgrading from ubuntu 16.04 to 18.04.
It was working on another virtual host before, and it doesn't work on the same host now. Contao running on this host do work as expected.
So far I' tried:
 downloaded the contao-manager.phar in many ways : by browser, by wget, by curl. All look exactly the same
- used it renaming to .phar.php, let as .phar, renamed to .php
- tried all sort of permissions on website folders.
- tried to move in and out of web folder
- tried on another virtual host (which IS running contao). BTW, on that site the contao-manager.phar.php was running before the update to ubuntu 18.04, now it doesn't run either. The website still runs ok.
- tried a self-update, which works and tells, correctly, that contao-manager is on latest version.
- searched the whole server for some useful log, nothing found. Just that browser console's useless message "uncaught exception (in promise)."
Website is running Apache and php 7.2 under ispconfig. Ì also tried 2 php modes, but no changes.

**Comment by MicioMax** [comment] 2018-10-10 09:08
.phar is supported. It was working before the update to 18.04.
You can check it at this address... https://www.timberstruct.eu/contao-manager.phar.php
And on same server I've a contao site (https://www.fishino.com) which is working fine. Just the manager stopped working after the update.

**Comment by MicioMax** [comment] 2018-10-10 09:13
I've also a phpinfo.php on same site, if it can help...  https://www.timberstruct.eu/phpinfo.php

**Comment by MicioMax** [comment] 2018-10-10 13:43
I'm testing it on a virtual machine, ubuntu 32 bit (16.04) with php7.0; same result.
The apache access log file shows that only 4 files are fetched:
`
127.0.0.1 - - [10/Oct/2018:15:38:25 +0200] "GET /contao-manager.phar.php/ HTTP/1.1" 200 528 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [10/Oct/2018:15:38:25 +0200] "GET /contao-manager.phar.php/assets/js/manifest.cf8a2d55d11ff4005963.js HTTP/1.1" 200 1073 "http://localhost/contao-manager.phar.php/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [10/Oct/2018:15:38:25 +0200] "GET /contao-manager.phar.php/assets/js/app.05f3e76d303b8cf9afaf.js HTTP/1.1" 200 47722 "http://localhost/contao-manager.phar.php/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [10/Oct/2018:15:38:25 +0200] "GET /contao-manager.phar.php/assets/js/vendor.69af660a7457adc594b3.js HTTP/1.1" 200 59687 "http://localhost/contao-manager.phar.php/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:55.0) Gecko/20100101 Firefox/55.0"
`
Same blank page, no errors on apache.error log, no other logs nor messages found.
If you can suggest some more test I can try them.

**Comment by MicioMax** [comment] 2018-10-10 15:15
Some news : i rolled back to FIRST beta (1.0.0-beta1) and it works in my localhost setup, also ubuntu 18.04 with apache and php7.2; latest release (1.4.0) and the former (1.3.0) don't.
I guess that means that's definitively not a problem in my server.
I'll try to narrow the issue.

**Comment by MicioMax** [comment] 2018-10-10 15:37
So, narrowed to transition between last beta (working, 1.0.0-beta19) and first non beta (not working, 1.0.0)

**Comment by MicioMax** [comment] 2018-10-11 13:19
I did a git bisect on the three, and found this as offending commit : 

`
b1a781330ffcd26a7b83ce9bde45937b4c3868d4 is the first bad commit
commit b1a781330ffcd26a7b83ce9bde45937b4c3868d4
Author: Andreas Schempp <andreas.schempp@terminal42.ch>
Date:   Tue May 29 09:16:39 2018 +0200

    Use the multilingual search index \o/

:040000 040000 d59087e286b8a6c41650fa78d0fc7c2df6f417ee 5c5b0c60e7d790ac4470d2208ad01f42b9a9ad36 M	src
`
I'm almost a noob on php/js development, but I'll try anyways to figure it out.

**Comment by MicioMax** [comment] 2018-10-11 13:34
I also disabled all language packs just now (as the commit is about multilingual...) but nothing.
Still the blank page.

**Comment by MicioMax** [comment] 2018-10-11 14:10
Hi,
if I patch src/i18n/index.js like this : 
`
export default {
    init() {
        let userLang = window.localStorage.getItem('contao_manager_locale');

        if (!userLang) {
            userLang = navigator.language || navigator.userLanguage;
        }

//        return this.load(userLang);
        return this.load('en');
    },

`
(just a blind try, I even don't lnow if userLang shall be a string) it works perfectly.
Tested on git head.
I really don't know what's happening there.

**Comment by aschempp** [comment] 2018-10-12 05:58
Do you get any javascript error messages in the console? Maybe your browser does not provide a default language?

**Comment by MicioMax** [comment] 2018-10-12 07:30
Just the "uncaught exception (in promise)" above... nothing else.
The exception is in inner js code, so I can't figure out from where it comes...

**Comment by MicioMax** [comment] 2018-10-12 07:56
Hi,
I tested on remote webserver, same behaviour, the white page.
But I noticed one thing : if I start my patched version before, and THEN I replace it with the official one, latter works. If I remove the cookies from browser it stops working again.
So, launching the patched version setup a couple of cookies that allow the official version to start... probably the forced "en" language. The manager language is, indeed, english.

**Comment by aschempp** [comment] 2018-10-15 06:56
Can you figure out which cookie it is?

**Comment by MicioMax** [comment] 2018-10-15 08:34
> Can you figure out which cookie it is?

Hmmm... I see 3 cookies, but I'm not sure they're related; then I see a couple of settings in "local storage", which may be related.
Here the cookies : 
![cookies_1](https://user-images.githubusercontent.com/1090851/46939134-ccbcce00-d065-11e8-9949-f767e48c0283.png)
And here the local storage data : 
![cookies_2](https://user-images.githubusercontent.com/1090851/46939146-db0aea00-d065-11e8-83a8-0f73e0e5f2b6.png)
I think it's the "contao_manager_locale" one.

**Comment by MicioMax** [comment] 2018-10-15 08:37
What I think is that the manager can't figure out the language; if I force it to "en", it stores it in local storage data and don't try to figure out again, so it works.
As I told you, I tested also on a remote server (rdesktop on it) which is located in Germany (here I'm in Italy), identical setup (ubuntu 18.04, browser Firefox, php 7.2 and so on), and I've the same identical issue.

**Comment by elenadatta** [comment] 2018-11-02 18:20
I have the same problem ... blank page when I try to use last Contao Manager on php 7.2 and php 7.1 (Ubuntu 18.04)... I've tried to install Contao with a very old contao-manager.phar file and it seem to work but after the updating of Contao Manager (is impossible bypass the updating ...) the blank page appear 
and I can not install contao ... 
I'm going crazy !!!!

**Comment by MicioMax** [comment] 2018-11-02 22:03
Just try the small patch above, forcing the language to whathever you want (I used 'en', but it should work with any language)

**Comment by aschempp** [comment] 2019-06-28 11:49
I debugged this an I'm unable to reproduce this problem. It has probably been fixed in the meantime.

**Closed by aschempp** 2019-06-28 11:49 UTC
Labels: hosting, question
