### ISSUE TITLE
Debug-Modus funktioniert nicht mehr 

### ISSUE THREAD

**Issue by pressi** [contao/contao-manager#613] opened 2020-11-29 19:44 UTC
Hallo!

Contao Version: 4.10.4
Manager Version: 1.3.3

Seit einem Update funktioniert der Debug-Modus nicht mehr.

![image](https://user-images.githubusercontent.com/1610762/100551802-6023de00-3283-11eb-9206-daf56e304cd5.png)

Error-Log Code:
`[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] request.INFO: Matched route "contao_managerapi_contao_jwtcookie__invoke". {"route":"contao_managerapi_contao_jwtcookie__invoke","route_parameters":{"_route":"contao_managerapi_contao_jwtcookie__invoke","_controller":"Contao\\ManagerApi\\Controller\\Contao\\JwtCookieController"},"request_uri":"https://update.original.plus/contao-manager.phar.php/api/contao/jwt-cookie","method":"PUT"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":3} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"stephan.pressl\", authenticated=true, roles=\"ROLE_ADMIN\"))","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:57] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[29-Nov-2020 20:40:58 Europe/Berlin] [2020-11-29 20:40:58] app.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The cookie name "Deprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 151  Deprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 151  Deprecated: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 471  Deprecated: Not specifying the signer and key to Builder#getToken() is deprecated. Please move the arguments from Builder#sign() to Builder#getToken(). in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 506 contao_settings" contains invalid characters." at phar:///usr/www/users/XXX/web/contao-manager.phar.php/vendor/symfony/http-foundation/Cookie.php line 102 {"exception":"[object] (InvalidArgumentException(code: 0): The cookie name \"Deprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 151\n\nDeprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 151\n\nDeprecated: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 471\n\nDeprecated: Not specifying the signer and key to Builder#getToken() is deprecated. Please move the arguments from Builder#sign() to Builder#getToken(). in /usr/www/users/XXX/vendor/lcobucci/jwt/src/Builder.php on line 506\ncontao_settings\" contains invalid characters. at phar:///usr/www/users/XXX/web/contao-manager.phar.php/vendor/symfony/http-foundation/Cookie.php:102)"} []`

Liebe Grüße 
pressi

**Comment by aschempp** [comment] 2020-11-30 07:36
Looks like a duplicate of https://github.com/contao/contao-manager/issues/612 ?

**Closed** 2021-01-02 09:12 UTC
