### ISSUE TITLE
CM 1.3.1: it´s not possible to delete any contao bundles

### ISSUE THREAD

**Issue by zonky2** [contao/contao-manager#272] opened 2018-06-08 13:32 UTC
it´s not possible to delete any contao bundles:

contao/calendar-bundle
contao/comments-bundle
contao/faq-bundle
contao/news-bundle
contao/newsletter-bundle

No response when you click on red button "Remove".

**Comment by Toflar** [comment] 2018-06-08 14:20
Can you check your JavaScript console and tell us if there are any errors there?

**Comment by zonky2** [comment] 2018-06-08 15:56
no error or warnungs - uBlock during test disabled...

**Comment by fkaminski** [comment] 2018-06-08 16:14
Maybe duplicate with #268

**Comment by zonky2** [comment] 2018-06-08 16:33
I don't think so.

**Comment by zonky2** [comment] 2018-06-09 12:29
If I comment out "display: none;" the button works

`<div tabindex="-1" class="button-group__group" style="/*! display: none; */">`

I test it wit FF 60 an Chrome 66 and Win 7

**Comment by fkaminski** [comment] 2018-06-09 17:19
Dito - seems to be just a frontend issue ...

**Comment by aschempp** [comment] 2018-06-18 12:29
Duplicate of https://github.com/contao/contao-manager/issues/268

**Closed by aschempp** 2018-06-18 12:29 UTC

**Comment by zonky2** [comment] 2018-06-18 12:45
wie in https://github.com/contao/contao-manager/issues/272#issuecomment-395965696 geschrieben, wenn man den Button das `display: none?` raus nimmt, gehts
