### ISSUE TITLE
Custom tables should be ignored

### ISSUE THREAD

**Issue by Funbug** [contao/contao-manager#750] opened 2022-12-06 22:26 UTC
Custom tables should not be marked for deletion by an update in the Contao Manager. Expected behaviour is that Contao only modifies and deletes its own tables begining with "tl_".

**Comment by cliffparnitzky** [comment] 2022-12-06 22:45
Duplicate of #746

@Funbug Have a look at the last comment. There you can find a solution how to configure.

**Comment by Funbug** [comment] 2022-12-06 22:48
Thanks you! Didn't see that one. 

I still think it should be default that Contao only touches its own tables.

**Comment by Toflar** [comment] 2022-12-06 23:15
It's not related to the Manager at all anyway. The Manager is just a GUI for the CLI.

**Comment by Funbug** [comment] 2022-12-06 23:17
My bad. I thought so, because the old install toll was not deleting custom tables.

**Comment by Toflar** [comment] 2022-12-06 23:17
Closing because it should be `contao/contao`, as should have been the other one referenced.

**Closed by Toflar** 2022-12-06 23:17 UTC
