### ISSUE TITLE
[Feature]: Unterstützung von glob-Patterns in "repositories"-Sektion

### ISSUE THREAD

**Issue by MacGyer** [contao/contao-manager#633] opened 2021-02-12 16:55 UTC
Hallo,

da ich aktuell mehrere Extensions für eine Contao-Instanz entwickele, habe ich die Angabe zum lokalen Spiegeln der Pakete im Composer-Schema mit einem glob-Pattern `*` angegeben. Dies ist von Composer direkt so vorgesehen (https://getcomposer.org/doc/05-repositories.md#path; Siehe letzte Notiz), leider kann der Manager **mit aktivierter Resolver-Cloud** damit nicht umgehen.

```json
"repositories": [
    {
        "type": "path",
        "url": "vendor_static/bundles/*",
        "options": {
            "symlink": true
        }
    },
],
```

Ist Support für glob-Patterns geplant?

Cheers

**Comment by fritzmg** [comment] 2021-02-12 18:43
The problem is not the glob pattern but the fact that you are using a local bundle. The resolver cloud has of course no access to these bundles. If yo use local bundles, you cannot use the resolver cloud.

**Comment by MacGyer** [comment] 2021-02-12 18:55
The following is working with resolver cloud:

```json
"repositories": [
    {
        "type": "path",
        "url": "vendor_static/bundles/bundle-1",
        "options": {
            "symlink": true
        }
    },
    {
        "type": "path",
        "url": "vendor_static/bundles/bundle-2",
        "options": {
            "symlink": true
        }
    },
],
```

So if I am specifying each local bundle with a path to the exact folder (relative to composer.json) the resolving is working like expected. Only using the glob pattern is not working.

Any thought?

**Comment by fritzmg** [comment] 2021-02-12 19:48
I wasn't aware that that works. @aschempp is the Contao Manager somehow sending information about the local bundles to the resolver cloud now?

**Comment by aschempp** [comment] 2021-02-13 08:08
yes, it is sending the content of composer.json of artifact and path repositories to the cloud to resolve its dependencies. That's how the ZIP upload works. I wasn't ware you can use glob patterns for the path, so that's not (yet) supported. Sure is something we can add though I guess 😊

**Comment by MacGyer** [comment] 2021-02-13 10:52
Thx for getting back and checking out the possibilities.

Have a nice weekend.

**Comment by aschempp** [comment] 2022-03-04 08:14
I just tried this locally and the resolve cloud seems to receive the correct repository results. I would therefore assume this has been fixed (e.g. in Composer 2.2) or is a cloud issue. I'm closing this for now, feel free to response/reopen if the issue still exists.

**Closed by aschempp** 2022-03-04 08:14 UTC
Labels: feature
