### ISSUE TITLE
Feature: Add settings for language shortcuts in the URLs

### ISSUE THREAD

**Issue by jankout** [contao/contao-manager#192] opened 2017-12-11 09:33 UTC
It would be great to have the possibility to set the language shortcuts for the URLs directly in the Contao Manager. Thank you.

**Comment by aschempp** [comment] 2017-12-11 10:02
You mean whether to use language prefixes? prependLanguage ?

**Comment by jankout** [comment] 2017-12-11 10:09
yes.

**Comment by aschempp** [comment] 2018-06-18 12:43
Duplicate of https://github.com/contao/contao-manager/issues/116

**Closed by aschempp** 2018-06-18 12:43 UTC
Labels: enhancement
