### ISSUE TITLE
Correctly detect the latest version to be installed

### ISSUE THREAD

**Issue by MDevster** [contao/contao-manager#754] opened 2022-12-22 11:29 UTC
Currently, we are receiving more and more requests that certain versions of extensions are not installable with Contao 4.13 LTS. This happens with all extensions that are only available for Contao 5 after a certain version. An example would be a fresh installation of Contao 4.13 and subsequent installation of the MATE theme.
The manager here always wants to install the latest version, but this is not released for Contao 4.13, he would have to install from the 2.x branch. So it would be advantageous if the manager already uses its existing information about the installation for the preselection of the correct version.

![grafik](https://user-images.githubusercontent.com/10244240/209121716-fee60052-a015-4986-8559-93b4b0ab88a4.png)

**Current unattractive solution**
The user must now always manually enter the latest ^2.19.

**Example Error**
```
Problem 1
    - Root composer.json requires contao-themes-net/mate-theme-bundle ^3.0 -> satisfiable by contao-themes-net/mate-theme-bundle[3.0.0, 3.0.1, 3.0.2, 3.0.3].
    - contao-themes-net/mate-theme-bundle[3.0.0, ..., 3.0.3] require contao/core-bundle ^5.0 -> found contao/core-bundle[5.0.0, ..., 5.0.7] but these were not loaded, likely because it conflicts with another require.
````

**Comment by Toflar** [comment] 2022-12-22 14:24
Duplicate of https://github.com/contao/contao-manager/issues/325.

**Closed by Toflar** 2022-12-22 14:24 UTC
