### ISSUE TITLE
The Contao Manager failed to start a console task!

### ISSUE THREAD

**Issue by rburch** [contao/contao-manager#296] opened 2018-06-25 14:04 UTC
Here's what I get: 

The Contao Manager failed to start a console task!
Something went wrong while trying to execute the task in the background.
If this happens again, your server might not be supported.

Resolving dependencies using Composer Cloud v1.3.3
Job ID 5b30f52d7a3a88.15720823 is running for 40 seconds

Also can't close the the window with the close button after. Nothing happens when clicking it.

**Comment by rburch** [comment] 2018-06-25 14:15
Went back and shut off composer cloud and it seems to work fine.

**Comment by hella-schu** [comment] 2018-07-03 13:10
Same here, but no console output at all (just "Warte auf Konsolenausgabe").
But I can run composer update via SSH / putty.

**Comment by aschempp** [comment] 2018-07-04 07:05
> But I can run composer update via SSH / putty.

Absolutely. Just run `/path/to/php /path/to/contao-manager.phar.php composer update`

**Comment by aschempp** [comment] 2018-07-17 14:32
Duplicate of #267

**Closed by aschempp** 2018-07-17 14:32 UTC
