### ISSUE TITLE
Can't upgrade to 4.13.41 -> error with "twig_escape_filter_is_safe()"

### ISSUE THREAD

**Issue by jochi44** [contao/contao-manager#805] opened 2024-04-16 17:05 UTC
When trying to update from 4.13.40 to 4.13.41 the following error is shown at the step "composer install":

`// Warming up the cache for the prod environment with debug false
18:59:02 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod --no-ansi". Message: "Call to undefined function Contao\CoreBundle\Twig\Extension\twig_escape_filter_is_safe()" ["exception" => Error { …},"command" => "cache:warmup --env=prod --no-ansi","message" => "Call to undefined function Contao\CoreBundle\Twig\Extension\twig_escape_filter_is_safe()"]
In ContaoExtension.php line 193:
  Attempted to call function "twig_escape_filter_is_safe" from namespace "Con  
  tao\CoreBundle\Twig\Extension".`

**Comment by ausi** [comment] 2024-04-17 10:22
Is this a duplicate of https://github.com/contao/contao/issues/7121 ?

**Closed** 2024-04-17 11:23 UTC
