### ISSUE TITLE
Installation of Contao: Password length not checked correctly

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao-manager#741] opened 2022-11-08 09:41 UTC
Hello, I found a usability bug when executing the contao-manager for the first time and using the auto-credential-fill-in feature of the browser:

**Steps to reproduce:**
1. Make fresh contao installation (call contao-manager.phar.php for the first time)
2. Use your browser's (Firefox) auto-fill-in password feature (my username and password (8 chars) are filled in automatically:
![grafik](https://user-images.githubusercontent.com/2657385/200529268-8cadf91e-4b90-4cf3-b5a9-a27cf9741496.png)
3. The button "Benutzerkonto erstellen" is still grey. No error message is triggered.

**Expectation:**
1. The Password field should be checked as soon as the browser fills in the stored credentials.
2. If there is an error and the Button is unclickable, I want to see the error message. What is wrong? What do I have to do against it? There is no hint for me (big frustration due to missing user feedback).

**Workaround:** I add one char to the password and delete it again: The button is green.

**Comment by fritzmg** [comment] 2022-11-08 09:45
Possibly duplicate of #734

**Comment by aschempp** [comment] 2022-11-16 11:48
this will be fixed/improved in the next version

**Closed by aschempp** 2022-11-16 11:48 UTC
