### ISSUE TITLE
Typo in Rebuilding Contao Cache

### ISSUE THREAD

**Issue by conversoft** [contao/contao-manager#623] opened 2021-01-12 20:59 UTC
When you rebuild cache via the manager it actually says vendor/bin/contao-con**C**ole cache:clear --no-warmup

**Comment by xchs** [comment] 2021-01-13 00:33
Isn't this a duplicate of https://github.com/contao/contao-manager/issues/603 ?

**Comment by aschempp** [comment] 2021-01-13 07:32
right! closing then as already fixed 😊

**Closed by aschempp** 2021-01-13 07:32 UTC
Labels: bug
